export const TOGGLE_STATUS = 'TOGGLE_STATUS';
export const FETCHING_DATA_ASYNCSTOAGE = 'FETCHING_DATA_ASYNCSTOAGE';

export const DATA_HS = 'DATA_HS';

export const NUMBER_NOTIFI = 'NUMBER_NOTIFI';
export const SET_NUMBER_NOTIFI = 'SET_NUMBER_NOTIFI';