export const TOGGLE_STATUS = 'TOGGLE_STATUS';
export const FETCHING_DATA_ASYNCSTOAGE = 'FETCHING_DATA_ASYNCSTOAGE';

export const DATA_HS = 'DATA_HS';

export const SET_NUMBER_NOTIFI = 'SET_NUMBER_NOTIFI';
export const TOKEN_ASYNC = 'TOKEN_ASYNC';
export const DATA_TOKEN = 'DATA_TOKEN';

export const SET_ROUTE = 'SET_ROUTE';

export const SET_NUMBER_ARR_NOTIFI = 'SET_NUMBER_ARR_NOTIFI';

export const SET_ID_PARAM_THONG_BAO= 'SET_ID_PARAM_THONG_BAO';
export const SET_ID_PARAM_DETAIL_MEDICINE= 'SET_ID_PARAM_DETAIL_MEDICINE';


